# aicage settings
AICAGE_IMAGE_REGISTRY: ghcr.io
AICAGE_IMAGE_REGISTRY_API_URL: https://ghcr.io/v2
AICAGE_IMAGE_REGISTRY_API_TOKEN_URL: https://ghcr.io/token?service=ghcr.io&scope=repository
AICAGE_IMAGE_BASE_REPOSITORY: aicage/aicage-image-base
AICAGE_IMAGE_REPOSITORY: aicage/aicage
